name: Pull upstream changes

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  pull:
    name: Pull upstream changes from raycast/extensions
    runs-on: ubuntu-latest
    steps:
      - uses: timrogers/pull-raycast-extension-changes@v1.0.0
        with:
          extension_name: clockify
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
